# Generated by Django 5.1.3 on 2024-11-05 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuaderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Color del cuaderno')),
                ('tipo', models.EmailField(db_column='Tipo_cuaderno', max_length=254)),
                ('diamametro', models.CharField(blank=True, max_length=20)),
                ('Precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Usuario')),
                ('cuenta', models.TextField(max_length=10, verbose_name='Cuenta Bancaria')),
                ('num_cuenta', models.TextField(unique=True)),
                ('fecha_registro', models.DateTimeField(db_column='fecha', default=django.utils.timezone.now)),
                ('usuario', models.ManyToManyField(related_name='Usuarios_cuadernos', to='examen.cuaderno')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios_Subscripto', to='examen.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vendidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('tipo', models.EmailField(max_length=254)),
                ('diamametro', models.CharField(blank=True, max_length=20)),
                ('Precio', models.FloatField()),
                ('vendidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendidos', to='examen.cuaderno')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion_cuadernos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_puntuacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('puntuacion', models.IntegerField()),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to='examen.usuario')),
                ('vendidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cuadernos_vendidos', to='examen.vendidos')),
            ],
        ),
    ]
