# Generated by Django 5.1.3 on 2024-11-05 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='usuarios',
        ),
        migrations.RemoveField(
            model_name='puntuacion_cuadernos',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='puntuacion_cuadernos',
            name='vendidos',
        ),
        migrations.AddField(
            model_name='puntuacion_cuadernos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios_puntuados', to='examen.usuario'),
        ),
        migrations.AddField(
            model_name='puntuacion_cuadernos',
            name='vendido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cuadernos_vendidos', to='examen.vendidos'),
        ),
    ]
